package classes;
// Generated Dec 16, 2013 11:52:22 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Analyse generated by hbm2java
 */
public class Analyse  implements java.io.Serializable {


     private Integer idAnalyse;
     private String codeAnalyse;
     private String nomAnalyse;
     private String domainAnalyse;
     private Set analysechamps = new HashSet(0);

    public Analyse() {
    }

	
    public Analyse(String codeAnalyse, String nomAnalyse, String domainAnalyse) {
        this.codeAnalyse = codeAnalyse;
        this.nomAnalyse = nomAnalyse;
        this.domainAnalyse = domainAnalyse;
    }
    public Analyse(String codeAnalyse, String nomAnalyse, String domainAnalyse, Set analysechamps) {
       this.codeAnalyse = codeAnalyse;
       this.nomAnalyse = nomAnalyse;
       this.domainAnalyse = domainAnalyse;
       this.analysechamps = analysechamps;
    }
   
    public Integer getIdAnalyse() {
        return this.idAnalyse;
    }
    
    public void setIdAnalyse(Integer idAnalyse) {
        this.idAnalyse = idAnalyse;
    }
    public String getCodeAnalyse() {
        return this.codeAnalyse;
    }
    
    public void setCodeAnalyse(String codeAnalyse) {
        this.codeAnalyse = codeAnalyse;
    }
    public String getNomAnalyse() {
        return this.nomAnalyse;
    }
    
    public void setNomAnalyse(String nomAnalyse) {
        this.nomAnalyse = nomAnalyse;
    }
    public String getDomainAnalyse() {
        return this.domainAnalyse;
    }
    
    public void setDomainAnalyse(String domainAnalyse) {
        this.domainAnalyse = domainAnalyse;
    }
    public Set getAnalysechamps() {
        return this.analysechamps;
    }
    
    public void setAnalysechamps(Set analysechamps) {
        this.analysechamps = analysechamps;
    }




}


