package classes;
// Generated Dec 16, 2013 11:52:22 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Champs generated by hbm2java
 */
public class Champs  implements java.io.Serializable {


     private Integer numeroChamp;
     private String champ;
     private String type;
     private Set analysechamps = new HashSet(0);

    public Champs() {
    }

	
    public Champs(String champ, String type) {
        this.champ = champ;
        this.type = type;
    }
    public Champs(String champ, String type, Set analysechamps) {
       this.champ = champ;
       this.type = type;
       this.analysechamps = analysechamps;
    }
   
    public Integer getNumeroChamp() {
        return this.numeroChamp;
    }
    
    public void setNumeroChamp(Integer numeroChamp) {
        this.numeroChamp = numeroChamp;
    }
    public String getChamp() {
        return this.champ;
    }
    
    public void setChamp(String champ) {
        this.champ = champ;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getAnalysechamps() {
        return this.analysechamps;
    }
    
    public void setAnalysechamps(Set analysechamps) {
        this.analysechamps = analysechamps;
    }




}


