package classes;
// Generated Dec 16, 2013 11:52:22 AM by Hibernate Tools 3.2.1.GA



/**
 * Coocurrences generated by hbm2java
 */
public class Coocurrences  implements java.io.Serializable {


     private Integer idCoocurrence;
     private int numero1;
     private int numero2;
     private int coOcurrence;
     private int date;

    public Coocurrences() {
    }

    public Coocurrences(int numero1, int numero2, int coOcurrence, int date) {
       this.numero1 = numero1;
       this.numero2 = numero2;
       this.coOcurrence = coOcurrence;
       this.date = date;
    }
   
    public Integer getIdCoocurrence() {
        return this.idCoocurrence;
    }
    
    public void setIdCoocurrence(Integer idCoocurrence) {
        this.idCoocurrence = idCoocurrence;
    }
    public int getNumero1() {
        return this.numero1;
    }
    
    public void setNumero1(int numero1) {
        this.numero1 = numero1;
    }
    public int getNumero2() {
        return this.numero2;
    }
    
    public void setNumero2(int numero2) {
        this.numero2 = numero2;
    }
    public int getCoOcurrence() {
        return this.coOcurrence;
    }
    
    public void setCoOcurrence(int coOcurrence) {
        this.coOcurrence = coOcurrence;
    }
    public int getDate() {
        return this.date;
    }
    
    public void setDate(int date) {
        this.date = date;
    }




}


