package classes;
// Generated Dec 16, 2013 11:52:22 AM by Hibernate Tools 3.2.1.GA



/**
 * Countrycodes generated by hbm2java
 */
public class Countrycodes  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String countryFr;
     private String countryEn;

    public Countrycodes() {
    }

    public Countrycodes(String code, String countryFr, String countryEn) {
       this.code = code;
       this.countryFr = countryFr;
       this.countryEn = countryEn;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getCountryFr() {
        return this.countryFr;
    }
    
    public void setCountryFr(String countryFr) {
        this.countryFr = countryFr;
    }
    public String getCountryEn() {
        return this.countryEn;
    }
    
    public void setCountryEn(String countryEn) {
        this.countryEn = countryEn;
    }




}


