package classes;
// Generated Dec 16, 2013 11:52:22 AM by Hibernate Tools 3.2.1.GA



/**
 * Items generated by hbm2java
 */
public class Items  implements java.io.Serializable {


     private Integer idItem;
     private Analysechamp analysechamp;
     private String nomLong;
     private String numeroItem;

    public Items() {
    }

    public Items(Analysechamp analysechamp, String nomLong, String numeroItem) {
       this.analysechamp = analysechamp;
       this.nomLong = nomLong;
       this.numeroItem = numeroItem;
    }
   
    public Integer getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(Integer idItem) {
        this.idItem = idItem;
    }
    public Analysechamp getAnalysechamp() {
        return this.analysechamp;
    }
    
    public void setAnalysechamp(Analysechamp analysechamp) {
        this.analysechamp = analysechamp;
    }
    public String getNomLong() {
        return this.nomLong;
    }
    
    public void setNomLong(String nomLong) {
        this.nomLong = nomLong;
    }
    public String getNumeroItem() {
        return this.numeroItem;
    }
    
    public void setNumeroItem(String numeroItem) {
        this.numeroItem = numeroItem;
    }




}


